version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Image tag is $IMAGE_TAG
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - |
        if [ -f "app/Dockerfile" ]; then
          cd app
          docker build -t $REPOSITORY_URI:latest .
          docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
          cd ..
        elif [ -f "Dockerfile" ]; then
          docker build -t $REPOSITORY_URI:latest .
          docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
        else
          echo "ERROR: Dockerfile not found!"
          exit 1
        fi
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - |
        cat > imageDetail.json <<EOF
        {
          "ImageURI": "$REPOSITORY_URI:$IMAGE_TAG"
        }
        EOF
      - cat imageDetail.json
      - echo Updating kubernetes deployment manifest...
      - |
        sed -i "s|image:.*|image: $REPOSITORY_URI:$IMAGE_TAG|g" kubernetes/deployment.yaml
      - cat kubernetes/deployment.yaml

artifacts:
  files:
    - '**/*'
  name: BuildArtifact

cache:
  paths:
    - '/root/.docker/**/*'

